controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
chart:
    path: /charts/moisture/{pot}
    controller: App\Controller\SensorController::chartPage
    methods: GET
