# This file is the entry point to configure your own services.

parameters:

services:
    # Default configuration for services
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Makes classes in src/ available as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Ensure controllers are public and have the correct tags
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
        public: true
